spring:
  application:
    name: DCF
  profiles:
    active: dev
#  webservices:
#    path: /dcf

  banner:
    charset: UTF-8
    location: classpath:banner.txt
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=300s
server:
  servlet:
   contextPath: /dcf


---

spring:
  profiles: dev
  environments: dev
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    restart:
      additonal-paths:
      exclude:

logging:
  file: dcf.log
  path: /log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file:
  level:
    org:
      hibernate:
        SQL: DEBUG

##Actuator
management:
  endpoints:
    enabled-by-default: false
#    httptrace:
#       enabled: true
  #    web:
  #      exposure:
  #        include: "*"

  #    metrics:
  #      id: springmetrics
  #      sensitive: false
  #      enabled: true
    web:
      cors:
        allowed-origins: http://example.com
        allowed-methods: GET,POST
  endpoint:
    info:
      enabled: true












